ego_scan_topic: '/scan'
ego_odom_topic: '/odom'
opp_odom_topic: '/opp_odom'
ego_drive_topic: '/drive'

lap_count_topic: '/lap_count'
lap_time_topic: '/lap_time'
collision_topic: '/collision'

race_info_topic: '/race_info'

# fixed vals DO NOT CHANGE
scan_fov: 4.7
scan_beams: 1080
scan_distance_to_base_link: 0.275

map_img_ext: '.png'
executable_dir: '/f1tenth_gym/build/'

# Vehicle physical Parameters: 
wheelbase       :   0.3302
mass            :   3.47
width           :   0.2032 # meters
l_r             :   0.17145 # m (decently measured to be 6.75 in)
I_z             :   0.04712 # kg m^2 (estimated as a rectangle with width and height of car and evenly distributed mass, then shifted to account for center of mass location)
mu              :   0.523 # - (friction_coeff- complete estimate)
h_cg            :   0.074 # m (roughly measured to be 3.25 in)
cs_f            :   4.718 #.79 # 1/rad ? (estimated weight/4)
cs_r            :   5.4562 #.79 # 1/rad ? (estimated weight/4)
l_cg2front: 0.15875 # m (decently measured to be 6.25 in)


# Limits on the speed and steering angle
max_speed: 7. #  meters/second
max_steering_angle: 0.4189 # radians
max_accel: 7.51 # meters/second^2
max_decel: 8.26 # meters/second^2
max_steering_vel: 3.2 # radians/second